# Generated by Django 3.2.4 on 2021-06-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='images',
            field=models.ImageField(blank=True, upload_to='user_images/'),
        ),
    ]
